# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
